### ISSUE TITLE
Format Template Part (Three-Steps) with PHP

### ISSUE THREAD

**Issue by reedar** [kingdom-one/k1-theme-v2#16]

**Comment by kjroelke** [comment]
@reedar can you say more about this?

**Comment by reedar** [comment]
@kjroelke This is another global block, but it needs to have the PHP added to it since the content changes (images and verbiage) based on the page it's used on. I created the proper files and called it in on the pages it was used on so far, it just needs to be set up so that you can write in the proper arguments for each page.
