### ISSUE TITLE
Nick Design List 

### ISSUE THREAD

**Issue by NickOvalle** [kingdom-one/k1-theme-v2#83]
- [x] Remove Logo from the Hamburger menu

- [x] Padding Space between hamburger menu and Get Started Butt..on

- [x] Remove k2 next to logo

- [x] Learn More button to link to About Us Page

- [x] HR Finance Marcom & Staffing icons link to pages.

- [x] Can the Relationship First Box auto scrolls to the second page

- [x] We're using our expertise to help ministries become more Courageous, Healthy, & Effective

- [x] Remove "Our pricing allows ministries of all sizes to participate in Kingdom One. Visit our pricing page to learn more about the costs and process." and 1,2 & 3 steps in Decide to Make section

- [x] #84

- [x] #85

- [x] Comms page - Update copy: "appearing desperate and needy by constantly posting event information" with "inconsistency, confusing copy & lack of strategy with a clear communication framework."

- [x] Comms Page - Recent Partnerships find on XD

- [x] Hide Pricing Page

- [x] Giving Page - Update Youtube video to https://youtu.be/IuNv15iBLBc

- [x] Get Started form code:
<div data-form-slug="2201480363848310" data-env="production" data-path="contact-us/2201480363848310" class="keap-custom-form"></div><script>(function(a,b){var c=a.keapForms||{SNIPPET_VERSION:"1.1.0",appId:"hav885"},d=b.createElement("script");d.type="text/javascript",d.crossOrigin="anonymous",d.defer=!0,d.src="https://forms.keap.app/lib/public-form-embed.js?appId=hav885&version=1.1.0",d.onload=function(){var b=a.keapForms;b.renderAllForms?!b.invoked&&(b.invoked=!0,b.renderAllForms()):console.error("[Keap Forms] Error: could not load")};var e=b.getElementsByTagName("script")[0];e.parentNode.insertBefore(d,e),a.keapForms=c})(window,document);</script>

- [x] Get Started page - Replace Steps 1,2&3 with "Your Healthy Ministry Plan Starts Here" on the About Page

- [x] #88

- [x] ERC page - Form: <div data-form-slug="2817083822916054" data-env="production" data-path="contact-us/2817083822916054" class="keap-custom-form"></div><script>(function(a,b){var c=a.keapForms||{SNIPPET_VERSION:"1.1.0",appId:"hav885"},d=b.createElement("script");d.type="text/javascript",d.crossOrigin="anonymous",d.defer=!0,d.src="https://forms.keap.app/lib/public-form-embed.js?appId=hav885&version=1.1.0",d.onload=function(){var b=a.keapForms;b.renderAllForms?!b.invoked&&(b.invoked=!0,b.renderAllForms()):console.error("[Keap Forms] Error: could not load")};var e=b.getElementsByTagName("script")[0];e.parentNode.insertBefore(d,e),a.keapForms=c})(window,document);</script>

- [x] ERC Secondary CTA: Find out your ERC Qualification with our ERC+ Checklist [Here](https://keap.page/hav885/erc-checklist.html).

- [x] ERC page - What is ERC copy on the page is greyed out, 

- [x] Above Reproach Page - Video: https://youtu.be/n14d6Addfas

- [x] #86

- [x] Home Page - Recent Partnership Section - Padding on Buttons

**Comment by kjroelke** [comment]
# Globals

- [x] Remove Site Title from Logo in header

# Pages

## Marcom

- [ ] Build swiper (#73)

## ERC

- [x] BUG: `<script>` doesn't work @NickOvalle 
- [x] Secondary CTA: Where does this go? @NickOvalle 

## Get-Started

- [x] Same `<script>` bug as ERC @NickOvalle 

## Share Your Story

- [x] Build CF7 form & integrate

# Live Environment

- [ ] Hide `/pricing`
- [x] Share Your Story CF7 Form Rebuild

**Comment by NickOvalle** [comment]
@kjroelke ERC Form

<div data-form-slug="3915198875505926" data-env="production" data-path="contact-us/3915198875505926" class="keap-custom-form"></div><script>(function(a,b){var c=a.keapForms||{SNIPPET_VERSION:"1.1.0",appId:"hav885"},d=b.createElement("script");d.type="text/javascript",d.crossOrigin="anonymous",d.defer=!0,d.src="https://forms.keap.app/lib/public-form-embed.js?appId=hav885&version=1.1.0",d.onload=function(){var b=a.keapForms;b.renderAllForms?!b.invoked&&(b.invoked=!0,b.renderAllForms()):console.error("[Keap Forms] Error: could not load")};var e=b.getElementsByTagName("script")[0];e.parentNode.insertBefore(d,e),a.keapForms=c})(window,document);</script>

**Comment by NickOvalle** [comment]
@kjroelke Get Started Form

<div data-form-slug="3915198875505926" data-env="production" data-path="contact-us/3915198875505926" class="keap-custom-form"></div><script>(function(a,b){var c=a.keapForms||{SNIPPET_VERSION:"1.1.0",appId:"hav885"},d=b.createElement("script");d.type="text/javascript",d.crossOrigin="anonymous",d.defer=!0,d.src="https://forms.keap.app/lib/public-form-embed.js?appId=hav885&version=1.1.0",d.onload=function(){var b=a.keapForms;b.renderAllForms?!b.invoked&&(b.invoked=!0,b.renderAllForms()):console.error("[Keap Forms] Error: could not load")};var e=b.getElementsByTagName("script")[0];e.parentNode.insertBefore(d,e),a.keapForms=c})(window,document);</script>

**Comment by NickOvalle** [comment]
@kjroelke 
Landing Page for Secondary CTA: https://keap.page/hav885/erc-checklist.html
